<?php

namespace AppBundle\Repository;

/**
 * clienteProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class clienteProductoRepository extends \Doctrine\ORM\EntityRepository
{
}
