<?php

namespace AppBundle\Repository;

/**
 * productoVentaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class productoVentaRepository extends \Doctrine\ORM\EntityRepository
{
}
